### ISSUE TITLE
Screening options can't be deleted from admin form

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#102]
When trying to delete existing screening options on /admin/config/services/opeka/screening (by just deleting the text) the javascript form validation requires the fields to be filled and does not allow the form to be submitted.

Only the first option should be required.

A workaround is to press the "Add option" button - this will delete the empty fields :-P

**Comment by alex-bukach** [comment]
@benjamin-dk I will provide "Remove" button (for each item), is it ok?

**Comment by cfdp** [comment]
@alex-bukach yes, that would be nice!

**Comment by alex-bukach** [comment]
@benjamin-dk done in https://github.com/cfdp/opeka/pull/109.

**Comment by gvd1** [comment]
merged in df1230ac
