### ISSUE TITLE
Reconnected client should have the same user alias as before

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#104]
When an anonymous user reconnects to a room he gets a new alias (e.g. anonymous34 instead of his original anonymous57).

This relates to #94 @alex-bukach

**Comment by cfdp** [comment]
At the moment I can't recreate this error @alex-bukach I'll let you know when/if I find the specific conditions.

**Comment by alex-bukach** [comment]
@benjamin-dk this was one of the points I tested carefully when implementing the reconnection, and it worked properly. I'm still not able to reproduce it on my side.
