### ISSUE TITLE
Add option for reporting user

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#137]
To be able to report chats where clients report criminal activity being committed against them in the way that least invades their privacy, we suggest implementing a new submodule "Opeka Report User" implementing the following feature:

* A report option is showed in the drop down menu along with "Ban user", "Mute user" etc.
* When the report action is chosen, a confirmation pop-up is shown to the counselor, saying "Do you really want to report this user? If so, give the reason below." In a text field in the popup, the counselor can write the reason for the report.
* If the counselor confirms, an email is sent to the Report Admin - an email-address chosen in the administration. The email will contain a link that, if clicked, will lead the Report Admin to the chat site and trigger the sending of an email to the Report Authority (typically the proper authority of the region where the chat is operated). This email-address is defined in the admin section of the module. This email can only be sent once per report done by the counselors.
* The content of the report sent to the Report Authority is defined by a template that can be customised in the admin section. It will contain the IP address, the User Agent and the date an time when the user accessed the chat.
* Notification emails are sent to the administrators of the site when a counselor chooses to report a user.

**Comment by cfdp** [comment]
fixed in ba113445c95
