### ISSUE TITLE
Opening hours should be managed via admin interface

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#53]
At the moment the opening hours are defined in a text field in the Drupal administration.

Users with the proper permissions should be able to define the opening hours in a more formal way so we can use the data to feed into other functionality e.g. embeddable widgets.

A way of doing this could be to create a custom sub module - Opeka Opening Hours, that define 

1. a new permission (Administer Opeka opening hours)
2. a new field on the Opeka administration page where users with the appropriate permissions can define the opening hours with a date picker of some sorts (granularity minutes).

The opening hours should be defined for a "standard week". This means that a number of time intervals can be defined, e.g.

Monday: 15-18
Monday: 21-22
Thursday: 14-16

There is no need for specific dates.

On the new opening hour admin page we furthermore need at text field for the counselors to insert a text like "You can chat with the counselors from Aarhus according to the following schedule".

The text field content and the opening hours should be made available to the widgets like it is now, see e.g. https://github.com/cfdp/opeka/blob/master/drupal_module/widgets/header/opeka--header-widget-page.tpl.php

The opening hours should be formatted nicely in a html list.

**Comment by cfdp** [comment]
Fixed in d9470bca0f
