### ISSUE TITLE
Screening questions on login form

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#58]
The purpose of this feature is to make the chat users supply certain information to the counselors before they login to the chat.

The information should be made available to the counselors in the chat via a foldout in the same interface element as where the age and gender info is stored.

The questions for getting the information are entered in the Opeka administation, Advanced Settings - or a dedicated tab, if that makes more sense.

The questions should be defined as a multiple choice field with a number of predefined answer options.

It should be possible to add any number of questions.

The questions should have two states (like nodes) published and unpublished. When unpublished, they will not be presented to the user.

It should also be possible to delete a question and all related data from the database.

It should be possible to define different question sets for 1-1 chats and group chats. 

The answers should be saved in the database together with date, age and gender.

**Comment by stefanospetrakis** [comment]
Sounds list sth Quiz-y => https://www.drupal.org/project/quiz
Or, is this expected to be custom coded?

**Comment by cfdp** [comment]
I was considering Webform integration, but maybe the quiz module is a better fit - I guess using the API would be the way to go, to ensure a smooth integration?

**Comment by stefanospetrakis** [comment]
A few more questions:

- Where is this Multiple Questions form supposed to appear? There is the '/opeka' main page, but this already loads the Javascript resources and may be a bit late to capture user's feedback via Drupal's Form API.
- Is the suggested idea to have a Drupal Form capture the data before loading/rendering the chat?
- Are the questions optional? Or, is access to the chat only possible after completing this step?
- The foldout that presents the information inside the chat is a Javascript/Chat component (I assume); is this expected to be delivered as part of this issue?

**Comment by gvd1** [comment]
Feature added in 6b376c0fa3b5c91ef71c665a10305d4135cf903f
