### ISSUE TITLE
Scrollbar jumps to bottom when dragged to top with "Pause auto-scroll" enabled

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#69]
With the "Pause auto-scroll" feature enabled in a chat room the scrollbar misbehaves under certain conditions: when  you manually drag the scroll-bar to the top, it will automatically jump to the bottom.

**Comment by alex-bukach** [comment]
@benjamin-dk resolved in #70.

**Comment by cfdp** [comment]
Fixed in e3c4d1ee90e2d
