### ISSUE TITLE
Messages not being rendered

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#74]
In some cases messages are not being rendered. The issue has been experienced on the develop branch.

I have found no exact way of reproducing this, but it happens quite reliably when creating a room, joining with two participants and just start sending messages rapidly by one of the participants.

At some point some messages will just not appear.

**Comment by alex-bukach** [comment]
@benjamin-dk Fixed in https://github.com/cfdp/opeka/pull/75. The issue was that when a message is being rendered, the window is in scrolling state, while new messages were not pushed to the messages list while scrolling.

**Comment by cfdp** [comment]
Fixed in #75
