### ISSUE TITLE
"Leave chat room" button conflicts with "Do you want to leave this site" popup

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#78]
When an anonymous user logs is in a chat room and chooses to leave by clicking the "Leave chat room" button, the warning "Do you want to leave this site" pops up.

Even though the user chooses to stay, she is logged out.

The preferred solution would be to disable the popup for this particular scenario.

**Comment by alex-bukach** [comment]
Fixed in https://github.com/cfdp/opeka/pull/81.
