### ISSUE TITLE
Drupal administration integration

### ISSUE THREAD

**Issue by DanielMM** [cfdp/opeka#8]
Allow the change of configuration options like opening hours, ban secret code, etc.

There are two sets of opening hours, one for each type of chat. The 1-to-1 chat has a regular schedule, all week days for a few hours. The group chat is going to take place on a session based that is made public beforehand with a few days.

Updated 22.06.2012 by @DanielMM

As each type of chat has a different schedule, we need to have two separate ways to manage them. I was thinking that it could be done in the administration(configuration) area under the WebServices > Opeka chat system, to have two textareas that will allow the input of the schedule for each type of chat.

As these values are stored in the database, we can retrieve them in a block and place them where we need.

The issue is more on how can we then output that data in snippet.html.

**Comment by cfdp** [comment]
This feature has been fixed https://github.com/cfdp/opeka/issues/53
