### ISSUE TITLE
Clients should not be able to log in when chat is closed

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#90]
Generally it should not be possible to see or join chat rooms for anonymous users when the chat is closed.

An exception to this rule is, that it should be possible to join private rooms, eg. via invitations even though the chat is closed.

In this way chats can be performed without the chat widget states being affected.

This information should be made available to the counselors in the UI.

**Comment by benjamin-dk** [comment]
Fixed in 532998a
