### ISSUE TITLE
Add column: 'session duration' to statistics table

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#96]
Currently we store the basic info that the regular chat clients give us when they log into the chat in the database.

We would like to add another column with the duration of the chat to the statistics table.

This information is already available as output in the message stream when a user logs out and it is currently also being written to the server log.

**Comment by alex-bukach** [comment]
@cfdp should we store it in minutes (as displayed in the log)?

**Comment by benjamin-dk** [comment]
@alex-bukach minutes is fine, yes.

**Comment by alex-bukach** [comment]
@cfdp done, please see https://github.com/cfdp/opeka/pull/97
