### ISSUE TITLE
Invitation date in email not being translated

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#98]
When sending out an invitation the time for the chat does not get translated to the site language (Danish) in the email message.

It displays as e.g. Thursday 22 June 2017, 17:20.

**Comment by benjamin-dk** [comment]
@alex-bukach do you have an idea how to fix this?

**Comment by alex-bukach** [comment]
@benjamin-dk @cfdp fixed in https://github.com/cfdp/opeka/pull/99.
